  api_version: 1
  runtime: nodejs
  vm: true

  health_check:
    enable_health_check: false

  handlers:

  - url: /(.+)
    static_files: app/\1
    upload: app/(.*)

  - url: /
    static_files: public/index.html
    upload: public/index.html

  skip_files:
  - ^(.*/)?app\.yaml
  - ^(.*/)?app\.yml
  - ^node_modules/(.*/)?
